### PR TITLE
Readme Fixes

### PR DESCRIPTION
**Pull request by grahamburgsma**
Fixing some issues I came across in the README.

- Composer package name
- Casing of MoesifAPIClient

### CODE REVIEW

**Comment by dgilling** [comment]
Thanks for the change. 

Quick question, I understand why moesifapi has to be changed to moesifapi-php, but what about the class name? 

Why does MoesifApiClient have to be changed to MoesifAPIClient?
I see the class name has Api as lower case in: https://github.com/Moesif/moesifapi-php/blob/master/src/MoesifAPIClient.php

Thanks,

Derric

**Comment by grahamburgsma** [comment]
Good catch. Looking at it again, the use statement has to change, but the class name doesn't.

`use MoesifApi\MoesifAPIClient`
`new MoesifApiClient`

So the best solution is to change the file name to match the class name. Do you agree on this change?

**Comment by dgilling** [comment]
Yes, will close PR, and change file name.

**Review by dgilling — APPROVED** [review]
Approved Fix 1:
rename moesifapi to moesifapi-php

**Pull request merged**
